component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/META-INF/services/.*
- ./bin/com/.*
- ./bin/com/jaspersoft/.*
- ./bin/com/jaspersoft/ireport/.*
- ./bin/com/jaspersoft/ireport/addons/.*
- ./bin/com/jaspersoft/ireport/addons/background/.*
- ./bin/com/jaspersoft/ireport/addons/callouts/.*
- ./bin/com/jaspersoft/ireport/addons/layers/.*
- ./bin/com/jaspersoft/ireport/addons/transformer/.*
- ./bin/com/jaspersoft/ireport/addons/transformer/tool/.*
- ./bin/com/jaspersoft/ireport/components/.*
- ./bin/com/jaspersoft/ireport/components/barcode/.*
- ./bin/com/jaspersoft/ireport/components/barcode/barbecue/.*
- ./bin/com/jaspersoft/ireport/components/barcode/barcode4j/.*
- ./bin/com/jaspersoft/ireport/components/barcode/icons/.*
- ./bin/com/jaspersoft/ireport/components/genericelement/.*
- ./bin/com/jaspersoft/ireport/components/list/.*
- ./bin/com/jaspersoft/ireport/components/spiderchart/.*
- ./bin/com/jaspersoft/ireport/components/spiderchart/properties/.*
- ./bin/com/jaspersoft/ireport/components/table/.*
- ./bin/com/jaspersoft/ireport/components/table/actions/.*
- ./bin/com/jaspersoft/ireport/components/table/nodes/.*
- ./bin/com/jaspersoft/ireport/components/table/nodes/properties/.*
- ./bin/com/jaspersoft/ireport/components/table/style/.*
- ./bin/com/jaspersoft/ireport/components/table/undo/.*
- ./bin/com/jaspersoft/ireport/components/table/widgets/.*
- ./bin/com/jaspersoft/ireport/components/table/wizard/.*
- ./bin/com/jaspersoft/ireport/designer/.*
- ./bin/com/jaspersoft/ireport/designer/actions/.*
- ./bin/com/jaspersoft/ireport/designer/borders/.*
- ./bin/com/jaspersoft/ireport/designer/charts/.*
- ./bin/com/jaspersoft/ireport/designer/charts/datasets/.*
- ./bin/com/jaspersoft/ireport/designer/charts/datasets/wizards/.*
- ./bin/com/jaspersoft/ireport/designer/charts/icons/.*
- ./bin/com/jaspersoft/ireport/designer/charts/multiaxis/.*
- ./bin/com/jaspersoft/ireport/designer/compatibility/.*
- ./bin/com/jaspersoft/ireport/designer/compiler/.*
- ./bin/com/jaspersoft/ireport/designer/compiler/prompt/.*
- ./bin/com/jaspersoft/ireport/designer/compiler/xml/.*
- ./bin/com/jaspersoft/ireport/designer/connection/.*
- ./bin/com/jaspersoft/ireport/designer/connection/gui/.*
- ./bin/com/jaspersoft/ireport/designer/crosstab/.*
- ./bin/com/jaspersoft/ireport/designer/crosstab/actions/.*
- ./bin/com/jaspersoft/ireport/designer/crosstab/undo/.*
- ./bin/com/jaspersoft/ireport/designer/crosstab/widgets/.*
- ./bin/com/jaspersoft/ireport/designer/crosstab/wizard/.*
- ./bin/com/jaspersoft/ireport/designer/data/.*
- ./bin/com/jaspersoft/ireport/designer/data/fieldsproviders/.*
- ./bin/com/jaspersoft/ireport/designer/data/fieldsproviders/ejbql/.*
- ./bin/com/jaspersoft/ireport/designer/data/fieldsproviders/hibernate/.*
- ./bin/com/jaspersoft/ireport/designer/data/fieldsproviders/olap/.*
- ./bin/com/jaspersoft/ireport/designer/data/fieldsproviders/xml/.*
- ./bin/com/jaspersoft/ireport/designer/data/queryexecuters/.*
- ./bin/com/jaspersoft/ireport/designer/dnd/.*
- ./bin/com/jaspersoft/ireport/designer/editor/.*
- ./bin/com/jaspersoft/ireport/designer/editor/functions/.*
- ./bin/com/jaspersoft/ireport/designer/errorhandler/.*
- ./bin/com/jaspersoft/ireport/designer/export/.*
- ./bin/com/jaspersoft/ireport/designer/fonts/.*
- ./bin/com/jaspersoft/ireport/designer/formatting/.*
- ./bin/com/jaspersoft/ireport/designer/formatting/actions/.*
- ./bin/com/jaspersoft/ireport/designer/jrctx/.*
- ./bin/com/jaspersoft/ireport/designer/jrctx/nodes/.*
- ./bin/com/jaspersoft/ireport/designer/jrctx/nodes/editors/.*
- ./bin/com/jaspersoft/ireport/designer/jrctx/nodes/properties/.*
- ./bin/com/jaspersoft/ireport/designer/jrtx/.*
- ./bin/com/jaspersoft/ireport/designer/logpane/.*
- ./bin/com/jaspersoft/ireport/designer/menu/.*
- ./bin/com/jaspersoft/ireport/designer/menu/preview/.*
- ./bin/com/jaspersoft/ireport/designer/options/.*
- ./bin/com/jaspersoft/ireport/designer/options/export/.*
- ./bin/com/jaspersoft/ireport/designer/options/jasperreports/.*
- ./bin/com/jaspersoft/ireport/designer/outline/.*
- ./bin/com/jaspersoft/ireport/designer/outline/nodes/.*
- ./bin/com/jaspersoft/ireport/designer/outline/nodes/properties/.*
- ./bin/com/jaspersoft/ireport/designer/outline/nodes/properties/charts/.*
- ./bin/com/jaspersoft/ireport/designer/palette/.*
- ./bin/com/jaspersoft/ireport/designer/palette/actions/.*
- ./bin/com/jaspersoft/ireport/designer/palette/actions/tools/.*
- ./bin/com/jaspersoft/ireport/designer/palette/items/.*
- ./bin/com/jaspersoft/ireport/designer/pdf508/.*
- ./bin/com/jaspersoft/ireport/designer/ruler/.*
- ./bin/com/jaspersoft/ireport/designer/sheet/.*
- ./bin/com/jaspersoft/ireport/designer/sheet/editors/.*
- ./bin/com/jaspersoft/ireport/designer/sheet/editors/box/.*
- ./bin/com/jaspersoft/ireport/designer/sheet/properties/.*
- ./bin/com/jaspersoft/ireport/designer/sheet/properties/charts/.*
- ./bin/com/jaspersoft/ireport/designer/sheet/properties/style/.*
- ./bin/com/jaspersoft/ireport/designer/standalone/.*
- ./bin/com/jaspersoft/ireport/designer/standalone/actions/.*
- ./bin/com/jaspersoft/ireport/designer/standalone/menu/.*
- ./bin/com/jaspersoft/ireport/designer/styles/.*
- ./bin/com/jaspersoft/ireport/designer/subreport/.*
- ./bin/com/jaspersoft/ireport/designer/templates/.*
- ./bin/com/jaspersoft/ireport/designer/toolbars/.*
- ./bin/com/jaspersoft/ireport/designer/tools/.*
- ./bin/com/jaspersoft/ireport/designer/undo/.*
- ./bin/com/jaspersoft/ireport/designer/utils/.*
- ./bin/com/jaspersoft/ireport/designer/welcome/.*
- ./bin/com/jaspersoft/ireport/designer/widgets/.*
- ./bin/com/jaspersoft/ireport/designer/widgets/visitor/.*
- ./bin/com/jaspersoft/ireport/designer/wizards/.*
- ./bin/com/jaspersoft/ireport/examples/.*
- ./bin/com/jaspersoft/ireport/examples/beans/.*
- ./bin/com/jaspersoft/ireport/examples/customcomponent/.*
- ./bin/com/jaspersoft/ireport/group/.*
- ./bin/com/jaspersoft/ireport/heartbeat/.*
- ./bin/com/jaspersoft/ireport/jasper/.*
- ./bin/com/jaspersoft/ireport/jasperserver/.*
- ./bin/com/jaspersoft/ireport/jasperserver/options/.*
- ./bin/com/jaspersoft/ireport/jasperserver/res/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/actions/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/inputcontrols/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/inputcontrols/impl/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/nodes/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/nodes/dnd/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ui/wizards/.*
- ./bin/com/jaspersoft/ireport/jasperserver/validation/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ws/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ws/scheduling/.*
- ./bin/com/jaspersoft/ireport/jasperserver/ws/util/.*
- ./bin/com/jaspersoft/ireport/locale/.*
- ./bin/com/jaspersoft/ireport/samples/.*
- ./bin/com/jaspersoft/ireport/samples/db/.*
- ./bin/com/jaspersoft/jrx/.*
- ./bin/net/.*
- ./bin/net/sf/.*
- ./bin/net/sf/jasperreports/.*
- ./bin/net/sf/jasperreports/engine/.*
- ./bin/net/sf/jasperreports/engine/images/.*
- ./branding/.*
- ./branding/core/.*
- ./branding/core/core.jar/.*
- ./branding/core/core.jar/org/.*
- ./branding/core/core.jar/org/netbeans/.*
- ./branding/core/core.jar/org/netbeans/core/.*
- ./branding/core/core.jar/org/netbeans/core/startup/.*
- ./branding/core/core.jar/org/netbeans/core/ui/.*
- ./branding/modules/.*
- ./branding/modules/org-netbeans-core-windows.jar/.*
- ./branding/modules/org-netbeans-core-windows.jar/org/.*
- ./branding/modules/org-netbeans-core-windows.jar/org/netbeans/.*
- ./branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/.*
- ./branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/.*
- ./branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/.*
- ./branding/modules/org-netbeans-core-windows.jar/org/netbeans/core/windows/view/ui/.*
- ./branding/modules/org-netbeans-core.jar/.*
- ./branding/modules/org-netbeans-core.jar/org/.*
- ./branding/modules/org-netbeans-core.jar/org/netbeans/.*
- ./branding/modules/org-netbeans-core.jar/org/netbeans/core/.*
- ./branding/modules/org-netbeans-core.jar/org/netbeans/core/ui/.*
- ./etc/.*
- ./heartbeat/.*
- ./heartbeat/nbproject/.*
- ./ireport-addons/.*
- ./ireport-addons/nbproject/.*
- ./ireport-designer/.*
- ./ireport-designer/nbproject/.*
- ./ireport-designer/release/.*
- ./ireport-designer/release/fonts/.*
- ./ireport-designer/release/libs/.*
- ./ireport-designer/release/modules/.*
- ./ireport-designer/release/modules/ext/.*
- ./ireport-designer/release/templates/.*
- ./ireport-designer/test/.*
- ./ireport-designer/test/unit/.*
- ./ireport-samples/.*
- ./ireport-samples/nbproject/.*
- ./ireport-samples/release/.*
- ./ireport-samples/release/database/.*
- ./ireport-samples/release/modules/.*
- ./ireport-samples/release/modules/ext/.*
- ./ireport-samples/release/samples/.*
- ./ireport-samples/release/samples/Basic_report/.*
- ./ireport-samples/release/samples/Charts/.*
- ./ireport-samples/release/samples/Charts/charts.html_files/.*
- ./ireport-samples/release/samples/Crosstabs/.*
- ./ireport-samples/release/samples/Elements/.*
- ./ireport-samples/release/samples/Elements/elements.html_files/.*
- ./ireport-samples/release/samples/Fonts/.*
- ./ireport-samples/release/samples/Groups/.*
- ./ireport-samples/release/samples/Groups/groups.html_files/.*
- ./ireport-samples/release/samples/Parameters_and_Variables/.*
- ./ireport-samples/release/samples/Parameters_and_Variables/parameters_and_variables.html_files/.*
- ./ireport-samples/release/samples/Subreports/.*
- ./ireport-standalone-specific/.*
- ./ireport-standalone-specific/nbproject/.*
- ./jasperreports-components/.*
- ./jasperreports-components/nbproject/.*
- ./jasperreports-extensions/.*
- ./jasperreports-extensions/nbproject/.*
- ./jasperreports-extensions/release/.*
- ./jasperreports-extensions/release/modules/.*
- ./jasperreports-extensions/release/modules/ext/.*
- ./jasperserver-plugin/.*
- ./jasperserver-plugin/nbproject/.*
- ./jasperserver-plugin/release/.*
- ./jasperserver-plugin/release/modules/.*
- ./jasperserver-plugin/release/modules/ext/.*
- ./nbproject/.*
